#THIS PYTHON FILE SHOW THE DATA ANALYSIS OF THE SALES DATA

In [1]:
import pandas as pd

#loading of the data and basic information of the data

In [2]:
data = pd.read_csv('data.csv') 
# load of the data
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      50 non-null     object
 1   Category  50 non-null     object
 2   Value     47 non-null     float64
 3   Product   50 non-null     object
 4   Sales     46 non-null     float64
 5   Region    50 non-null     object
dtypes: float64(2), object(4)
memory usage: 2.5+ KB
None

In [4]:
print(data.describe()) # for understanding the statistics of the data

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

Question 1: Basic Data Cleaning
In real-world data analysis, the very first step is almost always handling messy or missing data 
Task:

Write the code to load the data.csv file.

Write the code to find out exactly how many missing values are in each column.

Write the code to fill the missing values in the Sales column with the mean (average) of that column.

# BASIC 
#Q1  loading of the data has been earlier refer to cell 3 

# q2 find out the missing values in each column 
missingvalues = data.copy()

In [3]:
missingvalues = data.copy()
print("missing values in the data")
missingvalues.isnull().sum(axis=0)

missing values in the data

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [12]:
missingvalues.head(6)

         Date Category  Value   Product  Sales Region
0  01-01-2023        A   28.0  Product1  754.0   East
1  02-01-2023        B   39.0  Product3  110.0  North
2  03-01-2023        C   32.0  Product2  398.0   East
3  04-01-2023        B    8.0  Product1  522.0   East
4  05-01-2023        B   26.0  Product3  869.0  North
5  06-01-2023        B   54.0  Product3  192.0   West

In [ ]:
missingvalues['Sales'].fillna(missingvalues['Sales'].mean(), inplace=True)

# or we can also do this by using assiging same column to itself
missingvalues['Sales'] = missingvalues['Sales'].fillna(missingvalues['Sales'].mean())

Question 2: Mid-Level Aggregation
Now that your data is clean (let's assume we saved it as a DataFrame called df_clean), your Sales Manager has come to your desk with a few questions about performance.

This will test your ability to use .groupby() and the .agg() dictionary method we talked about earlier!

Your Task:


Write the code to group the data by Region, and find the Total (sum) of the Sales for each region.

Write the code to group the data by Product, and use the .agg() function to find two things at once:

The Average (mean) of the Value column.

The Maximum (max) of the Sales column.

In [15]:
# q1 
aggregateddata = missingvalues.groupby("Region")["Sales"].sum()
print("SUM OF THE SALES IN EACH REGION")
print(aggregateddata)

SUM OF THE SALES IN EACH REGION
Region
East     7574.130435
North    6565.130435
South    5158.000000
West     8559.260870
Name: Sales, dtype: float64

# THERE ARE TWO WAY OF DOING IT FOLLOWING IT IS -  >

In [ ]:
# syntax 
# dataframe.groupby().agg({"column1":"function1","column2":"function2"})
# in the agg function we can also give the name to the new column by using 
# dataframe.groupby().agg( NEWCOLUMN1 = ("column1","function1"), NEWCOLUMN2 = ("column2","function2") )

In [ ]:
missingvalues.groupby("Product").agg( MEANVALUES=("Value","mean"), MAXSALES=("Sales","max"))

          MEANVALUES  MAXSALES
Product
Product1   46.214286     938.0
Product2   52.800000     992.0
Product3   55.166667     949.0

In [ ]:
#q2 
productanalysis = missingvalues[["Value","Sales","Product"]]
print(productanalysis.head(6))
# 
print(productanalysis.groupby("Product")["Sales"].mean()) # for checking the total sales are same 
print(productanalysis.groupby("Product")["Value"].max())
productanalysis.groupby("Product").agg({"Value":"mean","Sales":"max"}).rename(columns={"Value":"MEANVALUE","Sales":"MAXSALES"})

   Value  Sales   Product
0   28.0  754.0  Product1
1   39.0  110.0  Product3
2   32.0  398.0  Product2
3    8.0  522.0  Product1
4   26.0  869.0  Product3
5   54.0  192.0  Product3
Product
Product1    573.758152
Product2    565.884058
Product3    536.217391
Name: Sales, dtype: float64
Product
Product1    97.0
Product2    99.0
Product3    96.0
Name: Value, dtype: float64

          MEANVALUE  MAXSALES
Product
Product1  46.214286     938.0
Product2  52.800000     992.0
Product3  55.166667     949.0

Question 3: Filtering & Subsetting (Mid-Level)
Now that you have mastered grouping and aggregating, Manager has come back with a new request. They don't want a summary table; they want to see the actual raw data, but only for the best-performing records in a specific location.

Your Task:

Write the code to filter the missingvalues DataFrame to only show rows where the Sales are greater than 600.

Bonus Challenge: Write the code to filter the DataFrame where Sales are greater than 600 AND the Region is exactly "East".

Print the number of rows (the length) of this final filtered DataFrame so the manager knows how many records met both criteria.

In [4]:
#q1
greater =data.copy()
greater

greater600= greater[greater["Sales"] <600]

In [5]:
bonus = greater600[(greater600["Sales"]<600)&(greater600["Region"]=="East")]

In [6]:
noof= len(bonus)
print("number of sales greater than 600 in east region is",noof)

number of sales greater than 600 in east region is 7

In [30]:
# for checking the number of the non null values in the dataframe

numberzero = data["Sales"].isna().sum()
print("number of non null values in the sales column is",numberzero)
print(type(numberzero))

# as we are using the greater as it the copy of the data 

zero = greater[greater["Sales"].isna()]

print("NULL VALUES IN THE SALES COLUMN")
print(zero)

number of non null values in the sales column is 4
<class 'numpy.int64'>
NULL VALUES IN THE SALES COLUMN
          Date Category  Value   Product  Sales Region
11  12-01-2023        B   60.0  Product2    NaN   West
33  03-02-2023        C   27.0  Product3    NaN   East
35  05-02-2023        B   60.0  Product2    NaN   West
37  07-02-2023        C    2.0  Product1    NaN  North

In [7]:
#  for checking the len of the we can also use the shape function
print(bonus.shape[0])

7

Question 4: Feature Engineering & Sorting (Mid-Level)
The Sales Manager is thrilled with your data pulls. Now, they want to do some actual performance analysis. Sometimes the data we need doesn't exist yet, so we have to invent it using the data we already have! This is called Feature Engineering.

Assume we are back to using our clean DataFrame (let's call it data). Let's assume the Value column actually represents the "Number of Units Sold."

Your Task:

Create a New Column: Write the code to create a brand new column in your DataFrame called Price_Per_Unit. This should be calculated by dividing the Sales column by the Value column.

Sort the Data: Write the code to sort the entire DataFrame by this new Price_Per_Unit column in descending order (meaning the highest price should be at the very top).

Show the Leaders: Write the code to display only the top 5 rows of this newly sorted DataFrame.

In [ ]:
# task four 
#creating a new column here
df=data.copy()
df["Price_Per_Unit"]=df["Sales"]/df["Value"]
print(df.head(6))

df.sort_values(by="Price_Per_Unit",ascending=False).head(5)

Question 1: Time Series & Dates (Advanced)
If you look at df.info() from earlier, the Date column is listed as an object (which means plain text/string). To do time analysis, Pandas needs to convert that plain text into a mathematical Date object.

Your Task:

Write the code to convert the Date column into real Pandas datetime format using pd.to_datetime(). (Hint: check the format of the dates in the file, like "01-01-2023").

Once it is converted, extract just the month number and put it into a brand new column called Month. (Hint: Pandas datetimes have a special .dt attribute just for this!)

Group the data by your new Month column and find the Total (sum) Sales for each month.

Question 2: The Pivot Table (Advanced)
Pivot Tables are the absolute gold standard for business reporting. Managers love them because they show two dimensions of data at once.

Your Task:

Write the code to create a Pivot Table using pd.pivot_table().

Set the rows (index) to be the Region.

Set the columns (columns) to be the Category.

Set the values to calculate the sum of Sales (you will need the aggfunc parameter).

Add a parameter to fill any missing/empty spots in the pivot table with a 0 instead of NaN.

Question 3: Conditional Logic & Bucketing (Advanced)
Sometimes you need to tag data based on specific rules. We want to categorize our sales into "High", "Medium", and "Low" buckets.

Your Task:
Write the code to create a new column called Performance.

If Sales > 700, it should say "High".

If Sales is between 400 and 700, it should say "Medium".

If Sales < 400, it should say "Low".

# checking where nan value exist therefore we use the isna().any()

In [ ]:
data.isna().sum(axis=0)
# data['Product']
# data[data[["Value","Sales"]].isna().sum(axis=1)>0]
data[data[["Value","Sales"]].isna().any(axis=1) ]

# print(data.head(6))

In [15]:
copydata  = data.copy()

In [14]:
copydata["Value"] = copydata["Value"].fillna(copydata["Value"].mean())
copydata["Sales"] = copydata["Sales"].fillna(copydata["Sales"].mean())

In [ ]:
copydata.info()
copydata

In [16]:
# copydata.astype({"Date":"datetime64"}) this is used for changing only the data type int and float
# changing the data type of the date column to datetime
copydata["Date"]=pd.to_datetime(copydata["Date"],format="%d-%m-%Y")

In [ ]:
copydata['Month'] = copydata["Date"].dt.month
copydata.head(6)

In [71]:
mothsales1 =copydata.groupby("Month")["Sales"].agg("sum","mean").rename("Total_Sales")
# print(type(monthsales1))
groupdata = copydata.groupby("Category")["Sales"].sum()

In [ ]:
print(groupdata) # <pandas.core.groupby.generic.DataFrameGroupBy object at 0x000001A468FF9010> why it is shown here then

In [ ]:
monthsales =copydata.groupby("Month")["Sales"].sum().rename("Total_Sales")
print(monthsales)
copydata.groupby("Month").agg(TOTAL_SALES=('Sales','sum'))
# print(type(monthsales))

In [44]:
pivot =copydata.pivot_table(index="Region",columns="Category",values="Sales",aggfunc="sum",fill_value=0)

In [ ]:
pivot

#TASK TO DONE

In [3]:
copydata = data.copy()

In [7]:
copydata[copydata[copydata.isna().any()]]


# here we are finding the rows where there is any na values

          Date Category  Value   Product  Sales Region
11  12-01-2023        B   60.0  Product2    NaN   West
15  16-01-2023        C    NaN  Product1  895.0  North
17  18-01-2023        C    NaN  Product1  108.0   West
28  29-01-2023        B    NaN  Product3  617.0  North
33  03-02-2023        C   27.0  Product3    NaN   East
35  05-02-2023        B   60.0  Product2    NaN   West
37  07-02-2023        C    2.0  Product1    NaN  North

In [ ]:
print(copydata["Date"])

In [ ]:
#task1 

copydata["Date"]=pd.to_datetime(copydata["Date"],format="%d-%m-%Y") 
# as i have converted the date here then why it comes in the format of 
# 2023-01-01
# 1    2023-01-02
# 2    2023-01-03
# 3    2023-01-04
# 4    2023-01-05
# 5    2023-01-06

In [20]:
copydata["Date"]
copydata["month"] = copydata["Date"].dt.month

In [23]:
salesbymonth =copydata.groupby("month").agg(Sales_sum =("Sales","sum"))

In [ ]:
salesbymonth

Question 2: The Pivot Table (Advanced)
Pivot Tables are the absolute gold standard for business reporting. Managers love them because they show two dimensions of data at once.

Your Task:

Write the code to create a Pivot Table using pd.pivot_table().

Set the rows (index) to be the Region.

Set the columns (columns) to be the Category.

Set the values to calculate the sum of Sales (you will need the aggfunc parameter).

Add a parameter to fill any missing/empty spots in the pivot table with a 0 instead of NaN.

In [25]:
pivottable= pd.pivot_table(copydata,index="Region",columns="Category",values="Sales",aggfunc="sum",fill_value=0)

In [26]:
# let try the task 3 .

In [30]:
copydata["performance"] =copydata["Sales"].apply(lambda x:"HIGH" if x>700 else "Medium" if x<700 and x>400 else "low" if x>300 else "low")

In [33]:
print(type(copydata["performance"]))

<class 'pandas.core.series.Series'>

In [43]:
import numpy as np

# If > 700, "High". 
# Else, if > 400, "Medium". 
# Else, "Low".
copydata["performance"] = np.where(copydata["Sales"] > 700, "High", 
                          np.where(copydata["Sales"] > 400, "Medium", 
                                   "Low"))

In [45]:
# task 3 can also be done by using np.where function 
import numpy as np
copydata["performance"] = np.where(copydata["Sales"]> 700 ,"HIGH", 
                                   np.where(copydata["Sales"]>400,"Medium","Low"))

In [47]:
# we are using the pd.cut 
copydata["performance"] =pd.cut(copydata["Sales"], bins=[-float("inf"), 400, 700, float("inf")], labels=["Low", "Medium", "High"])

In [48]:
copydata

,Date,Category,Value,Product,Sales,Region,month,performance
0,2023-01-01,A,28.000000,Product1,754.000000,East,1,High
1,2023-01-02,B,39.000000,Product3,110.000000,North,1,Low
2,2023-01-03,C,32.000000,Product2,398.000000,East,1,Low
3,2023-01-04,B,8.000000,Product1,522.000000,East,1,Medium
4,2023-01-05,B,26.000000,Product3,869.000000,North,1,High
5,2023-01-06,B,54.000000,Product3,192.000000,West,1,Low
6,2023-01-07,A,16.000000,Product1,936.000000,East,1,High
7,2023-01-08,C,89.000000,Product1,488.000000,West,1,Medium
8,2023-01-09,C,37.000000,Product3,772.000000,West,1,High
9,2023-01-10,A,22.000000,Product2,834.000000,West,1,High
10,2023-01-11,B,7.000000,Product1,842.000000,North,1,High
11,2023-01-12,B,60.000000,Product2,557.130435,West,1,Medium
12,2023-01-13,A,70.000000,Product3,628.000000,South,1,Medium
13,2023-01-14,A,69.000000,Product1,423.000000,East,1,Medium
14,2023-01-15,A,47.000000,Product2,893.000000,West,1,High
15,2023-01-16,C,51.744681,Product1,895.000000,North,1,High
16,2023-01-17,C,93.000000,Product2,511.000000,South,1,Medium
17,2023-01-18,C,51.744681,Product1,108.000000,West,1,Low
18,2023-01-19,A,31.000000,Product2,578.000000,West,1,Medium
19,2023-01-20,A,59.000000,Product1,736.000000,East,1,High
20,2023-01-21,C,82.000000,Product3,606.000000,South,1,Medium
21,2023-01-22,C,37.000000,Product2,992.000000,South,1,High
22,2023-01-23,B,62.000000,Product3,942.000000,North,1,High
23,2023-01-24,C,92.000000,Product2,342.000000,West,1,Low
24,2023-01-25,A,24.000000,Product2,458.000000,East,1,Medium
25,2023-01-26,C,95.000000,Product1,584.000000,West,1,Medium
26,2023-01-27,C,71.000000,Product2,619.000000,North,1,Medium
27,2023-01-28,C,56.000000,Product2,224.000000,North,1,Low
28,2023-01-29,B,51.744681,Product3,617.000000,North,1,Medium
29,2023-01-30,C,51.000000,Product2,737.000000,South,1,High
30,2023-01-31,B,50.000000,Product3,735.000000,West,1,High
31,2023-02-01,A,17.000000,Product2,189.000000,West,2,Low
32,2023-02-02,B,63.000000,Product3,338.000000,South,2,Low
33,2023-02-03,C,27.000000,Product3,557.130435,East,2,Medium
34,2023-02-04,C,70.000000,Product3,669.000000,West,2,Medium
35,2023-02-05,B,60.000000,Product2,557.130435,West,2,Medium
36,2023-02-06,C,36.000000,Product3,177.000000,East,2,Low
37,2023-02-07,C,2.000000,Product1,557.130435,North,2,Medium
38,2023-02-08,C,94.000000,Product1,408.000000,South,2,Medium
39,2023-02-09,A,62.000000,Product1,155.000000,West,2,Low
40,2023-02-10,B,15.000000,Product1,578.000000,East,2,Medium
41,2023-02-11,C,97.000000,Product1,256.000000,East,2,Low
42,2023-02-12,A,93.000000,Product3,164.000000,West,2,Low
43,2023-02-13,A,43.000000,Product3,949.000000,East,2,High
44,2023-02-14,A,96.000000,Product3,830.000000,East,2,High
45,2023-02-15,B,99.000000,Product2,599.000000,West,2,Medium
46,2023-02-16,B,6.000000,Product1,938.000000,South,2,High
47,2023-02-17,B,69.000000,Product3,143.000000,West,2,Low
48,2023-02-18,C,65.000000,Product3,182.000000,North,2,Low
49,2023-02-19,C,11.000000,Product3,708.000000,North,2,High